### ISSUE TITLE
Update to new NPM version

### ISSUE THREAD

**Issue by wsargent** [webjars/npm#3]
Looks like the latest version of NPM is 3.5.2.  The newest 2.4.x release is NPM version v2.14.14.  List of releases is here: https://github.com/npm/npm/releases

The latest version of NPM in webjars is 2.11.2: https://github.com/webjars/npm/blob/master/pom.xml#L43

There's a client who is looking for an upgraded version, so I'll see about upgrading (hopefully we just change the pom.xml and then publish this again).

**Comment by jamesward** [comment]
Fixed by #4 

Thanks @wsargent
